# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "mozodev/bionic64-anyenv"
  config.vm.network "forwarded_port", guest: 1313, host: 1313
  # config.vm.synced_folder ".", "/vagrant", exclude: ["node_modules"]

  config.vm.provider "virtualbox" do |vb|
    vb.name = "eplabor"
    vb.memory = "1024"
    # vb.linked_clone = true
  end

  # config.vm.provision "shell", path: "../provision/1-bootstrap.sh"
  # config.vm.provision "shell", path: "../provision/2-linuxbrew.sh", privileged: false
  # config.vm.provision "shell", path: "../provision/3-nvm.sh", privileged: false

  # config.vagrant.plugins = ["vagrant-fsnotify"]
  # config.trigger.after :up do |t|
  #   t.name = "vagrant-fsnotify"
  #   t.run = { inline: "vagrant fsnotify" }
  # end
  
end
