Project eplabor_admin {
  database_type: 'MariaDB'
  Note: '은평구노동자종합지원센터 상담, 교육 관리시스템'
}

Table "eplabor_consultings" {
  // directus 필드를 제회하고는 모두 암호화 필요
  "id" int(15) [pk, not null, increment, note: 'directus']
  "status" varchar(20) [not null, default: "draft", note: 'directus']
  "sort" int(10) [note: 'directus']
  "owner" int(10) [note: 'directus']
  "created_on" datetime [note: 'directus']
  "modified_by" int(10) [note: 'directus']
  "modified_on" datetime [note: 'directus']
  // 인적사항
  "applicant_name" varchar(200) [not null, note: '성명']
  "applicant_email" varchar(200) [note: '이메일 (id@domain.com)']
  "applicant_phone" varchar(200) [note: '전화번호 (010-000-0000)']
  // 노동 환경
  "company_name" varchar(250) [note: '사업장명']
  "company_owner" varchar(250) [note: '대표자명']
  "company_size" varchar(100) [note: '근로자수(무응답, 5인 미만, 5인이상 10인 미만, 10인 이상 30인 미만, 30인 이상 100인 미만, 100인 이상 )']
  "company_contact" varchar(250) [note: '연락처']
  "company_region" varchar(20) [note: '소재지(은평구, 기타, 무응답)']
  "company_sector" varchar(100) [note: '업종']
  "company_years" varchar(250) [note: '운영기간']
  "has_contract" varchar(100) [note: '근로계약서 작성여부 (작성, 미작성, 미교부, 무응답, 일부작성)']
  "has_social_insurance" varchar(100) [note: '근로계약서 작성여부 (작성, 미작성, 미교부, 무응답, 일부작성)']
  "has_employment_rules" varchar(100) [note: '근로계약서 작성여부 (작성, 미작성, 미교부, 무응답, 일부작성)']
  // 상담 내용
  "consulting_category" varchar(100) [note: '상담 유형']
  "consulting_subject" varchar(2000) [not null, note: '상담 및 문제 내용(long text)']
  // 관리자 영역
  "consulting_comment" varchar(2000) [not null, note: '상담 답변 및 관리자 메모(long text)']
  "consulting_status" varchar(100) [note: '근로계약서 작성여부 (작성, 미작성, 미교부, 무응답, 일부작성)']
  Note: '노동 상담'
}

Table "eplabor_workshops_participants" {
  "id" int(15) [pk, not null, increment]
  "status" varchar(20) [not null, default: "draft"]
  "sort" int(10) [default: NULL]
  "owner" int(10) [default: NULL]
  "created_on" datetime [default: NULL]
  "modified_by" int(10) [default: NULL]
  "modified_on" datetime [default: NULL]
  "name" varchar(200) [note: '교육신청 참여자']
  "email" varchar(200) [note: '교육신청 참여자']
  "class_id" varchar(200) [note: ' class-id: 교육프로그램 id(연결된 교육프로그램)']
}
