backend:
  name: git-gateway
  branch: master
  # name: test-repo
local_backend: true

media_folder: "homepage/static/uploads"
public_folder: "/uploads"

collections:
  - label: "설정"
    name: "settings"
    files:
      - name: "basic"
        label: "기본 정보"
        file: "homepage/data/eplabor.yml"
        fields:
          - {label: "법인명", name: "title", widget: "string"}
          - {label: "태그라인", name: "tagline", widget: "string"}
          - {label: "전화번호", name: "tel", widget: "string"}
          - {label: "팩스", name: "fax", widget: "string"}
          - {label: "이메일", name: "email", widget: "string"}
          - {label: "대표자", name: "representative", widget: "string"}
          - {label: "주소", name: "location", widget: "string"}
          - {label: "푸터", name: "footer", widget: "markdown"}
      - name: "front"
        label: "홈페이지"
        file: "homepage/data/front.yml"
        fields:
          - label: "슬라이드"
            name: "slides"
            widget: "list"
            fields:
              - {label: "슬라이드 제목", name: "title", widget: "string"}
              - {label: "슬라이드 설명글", name: "description", widget: "string"}
              - {label: "슬라이드 배경이미지", name: "bg", widget: "image"}
              - {label: "슬라이드 버튼 텍스트", name: "btn_text", widget: "string"}
              - {label: "슬라이드 버튼 링크", name: "btn_url", widget: "string"}
          - label: "센터 정보 블록"
            name: "center_info"
            widget: "list"
            fields:
              - {label: "제목", name: "title", widget: "string"}
              - {label: "아이콘", name: "icon", widget: "string"}
              - {label: "링크", name: "url", widget: "string"}
          - label: "최신 글 3개"
            description: "3개 넘어도 3개만 출력합니다."
            name: "recents"
            widget: "list"
            fields:
              - {label: "아이콘", name: "icon", widget: "string"}
              - {label: "제목", name: "title", widget: "string"}
              - {label: "게시판 유형", name: "type", widget: "string"}

  - label: "센터소개"
    name: "about"
    folder: "homepage/content/about/"
    extension: "md"
    fields:
      - {label: "제목", name: "title", widget: "string"}
      - {label: "작성일", name: "date", widget: "datetime"}
      - {label: "본문", name: "body", widget: "markdown"}

  - label: "공지사항"
    name: "notices"
    folder: "homepage/content/allim/notices"
    create: true
    slug: "{{slug}}"
    extension: "md"
    fields:
      - {label: "제목", name: "title", widget: "string"}
      - {label: "작성일", name: "date", widget: "datetime"}
      - label: "본문"
        name: "body"
        widget: ncw-tiny-mce
        tiny_config:
          apiKey: engl1s97gj9hrxpoa7eh7z5f05ozxfm1box3nxkh4j7a43ei
      - {label: "유형", name: "type", widget: "string", default: "notice"}
      - {label: "레이아웃", name: "layout", widget: "string", default: "section_single"}
      - label: "첨부파일"
        name: "files"
        widget: "file"
        required: false
        allow_multiple: true
        media_library:
          config:
            multiple: true

  - label: "센터소식"
    name: "news"
    folder: "homepage/content/allim/news"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "제목", name: "title", widget: "string"}
      - {label: "작성일", name: "date", widget: "datetime"}
      - label: "본문"
        name: "body"
        widget: ncw-tiny-mce
        tiny_config:
          apiKey: engl1s97gj9hrxpoa7eh7z5f05ozxfm1box3nxkh4j7a43ei
      - {label: "유형", name: "type", widget: "string", default: "news"}
      - {label: "레이아웃", name: "layout", widget: "string", default: "section_single"}

  - label: "자료실"
    name: "downloads"
    folder: "homepage/content/allim/downloads"
    create: true
    slug: "{{slug}}"
    extension: "md"
    fields:
      - {label: "제목", name: "title", widget: "string"}
      - {label: "작성일", name: "date", widget: "datetime"}
      - {label: "본문", name: "body", widget: "markdown"}
      - {label: "유형", name: "type", widget: "string", default: "download"}
      - {label: "레이아웃", name: "layout", widget: "string", default: "section_single"}
      - label: "첨부파일"
        name: "files"
        widget: "file"
        required: false
        allow_multiple: true
        media_library:
          config:
            multiple: true

  - label: "발간자료"
    name: "publications"
    folder: "homepage/content/allim/publications"
    create: true
    slug: "{{slug}}"
    extension: "md"
    fields:
      - {label: "제목", name: "title", widget: "string"}
      - {label: "작성일", name: "date", widget: "datetime"}
      - {label: "본문", name: "body", widget: "markdown"}
      - {label: "유형", name: "type", widget: "string", default: "publication"}
      - {label: "레이아웃", name: "layout", widget: "string", default: "section_single"}
      - label: "첨부파일"
        name: "files"
        widget: "file"
        required: false
        allow_multiple: true
        media_library:
          config:
            multiple: true

  - label: "교육신청"
    name: "workshops"
    folder: "homepage/content/workshops"
    create: true
    slug: "{{slug}}"
    extension: "md"
    fields:
      - {label: "제목", name: "title", widget: "string"}
      - {label: "작성일", name: "date", widget: "datetime"}
      - {label: "본문", name: "body", widget: "markdown"}
      - {label: "상태", name: "status", widget: "boolean", hint: "ON 신청 중, OFF 신청 마감"}
      - {label: "유형", name: "type", widget: "string", default: "workshop"}
      - label: "교육 정보"
        name: "workshop"
        widget: "object"
        fields:
          - {label: "이미지", name: "이미지", widget: "image"}
          - {label: "대상", name: "대상", widget: "string"}
          - {label: "일시", name: "일시", widget: "string"}
          - {label: "장소", name: "장소", widget: "string"}
          - {label: "신청기간", name: "신청기간", widget: "string"}
          - {label: "문의", name: "문의", widget: "string"}

  - label: "노동상담"
    name: "consulting"
    files:
      - label: "이용안내"
        name: "consulting-info"
        file: "homepage/content/consulting/info.md"
        fields:
          - {label: "제목", name: "title", widget: "string"}
          - {label: "작성일", name: "date", widget: "datetime"}
          - {label: "본문", name: "body", widget: "markdown"}
          - {label: "레이아웃", name: "layout", widget: "string", default: "section_single"}
